before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq autoconf-archive
    - sudo apt-get install -qq check automake autoconf
language: c
compiler:
    - gcc
    - clang
# Change this to your needs
script: 
    autoreconf --install &&
    ./configure && make check
